trigger:
- none

jobs:
- job: DOWNLOAD_DEPS
  steps:
  - checkout: self

  # download windows dependencies
  - bash: |
      cd ./Dependencies/IGraphics/
      ./download-igraphics-libs-win.sh
    displayName: Download Windows Dependencies

- job: WIN_DEPS
  dependsOn: DOWNLOAD_DEPS
  strategy:
    matrix:
      # x86_RELEASE:
      #   buildPlatform: 'Win32'
      #   buildConfiguration: 'Release'
      x64_RELEASE:
        buildPlatform: 'x64'
        buildConfiguration: 'Release'
      # x86_DEBUG:
      #   buildPlatform: 'Win32'
      #   buildConfiguration: 'Debug'
      x64_DEBUG:
        buildPlatform: 'x64'
        buildConfiguration: 'Debug'

  pool:
    vmImage: 'vs2017-win2016'
  steps:
  # build x64 windows dependencies
  - task: VSBuild@1
    inputs:
      solution: 'Dependencies/IGraphics/IGraphicsLibraries.sln' 
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
    displayName: Build Windows Dependencies

  - task: DeleteFiles@1
    inputs:
      contents: 'Dependencies/Build/tmp'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'IPLUG2_DEPS_WIN'
      targetPath: 'Dependencies/Build/'
    displayName: Publish Windows Dependencies Artifacts
  
  # - task: ArchiveFiles@2
  #   inputs:
  #     rootFolderOrFile: Dependencies/Build/
  #     archiveFile: iplug2_deps_win.zip
  #   displayName: Archive Windows Dependencies

  # - task: CopyFiles@2
  #   inputs:
  #     contents: iplug2_deps_win.zip
  #     targetFolder: $(Build.ArtifactStagingDirectory)
  #   displayName: Copy Windows Dependencies Artifacts

  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     artifactName: 'IPLUG2_DEPS_WIN'
  #     pathtoPublish: $(Build.ArtifactStagingDirectory)
  #   displayName: Publish Windows Dependencies Artifacts


