trigger:
- master

jobs:
- job: Build
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.13'
        isMac: true
#      windows:
#        imageName: 'vs2017-win2016'
#        isWindows: true
#      linux:
#      imageName: 'ubuntu-16.04'
#        isLinux: true

  pool:
    vmImage: $(imageName)
    
  steps:
  - checkout: self

  # - bash: |
  #     ./Dependencies/IGraphics/build-igraphics-libs-mac.sh
  #   condition: variables.isMac
  #   displayName: Build macOS IGraphics Dependencies

  - bash: |
      ./Dependencies/Extras/faust/build-faust-mac.sh
    condition: variables.isMac
    displayName: Build macOS Extras Dependencies - FAUST

  - bash: |
      ./Dependencies/Extras/civetweb/build-civetweb-mac.sh
    condition: variables.isMac
    displayName: Build macOS Extras Dependencies - CIVETWEB

  - bash: |
      cd ./Dependencies/
      tar -cvzf iplug2_deps_macOS.tar.gz mac
    condition: variables.isMac
    displayName: Package macOS Dependencies Artifacts

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'IPLUG2_DEPS_MACOS'
      targetPath: './Dependencies/Build/iplug2_deps_macOS.tar.gz'
    condition: variables.isMac
    displayName: Publish macOS Dependencies Artifacts

  
#  - task: Xcode@5
#    inputs:
#      actions: 'build'
#      scheme: 'APP'
#      sdk: 'macosx10.13'
#      configuration: 'Release'
#      xcWorkspacePath: 'Tests/IGraphicsTest/IGraphicsTest.xcworkspace'
#      xcodeVersion: "9"
