trigger:
- none

jobs:
- job: DOWNLOAD_DEPS
  steps:
  - checkout: self

  # download windows dependencies
  - bash: |
      cd ./Dependencies/IGraphics/
      ./download-igraphics-libs-win.sh
    displayName: Download Windows Dependencies

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'SRC_WIN'
    displayName: Publish Source

- job: BUILD_WIN_DEPS
  dependsOn: DOWNLOAD_DEPS 
  strategy:
    matrix:
      x86_RELEASE:
        buildPlatform: 'Win32'
        buildConfiguration: 'Release'
      x64_RELEASE:
        buildPlatform: 'x64'
        buildConfiguration: 'Release'
      x86_DEBUG:
        buildPlatform: 'Win32'
        buildConfiguration: 'Debug'
      x64_DEBUG:
        buildPlatform: 'x64'
        buildConfiguration: 'Debug'

  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'SRC_WIN' 

  # build windows dependencies
  - task: VSBuild@1
    inputs:
      solution: 'Dependencies/IGraphics/IGraphicsLibraries.sln' 
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
    displayName: Build Windows Dependencies

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'DEPS_BUILD_WIN_$(buildPlatform)_$(buildConfiguration)'
      targetPath: 'Dependencies/Build/'
    displayName: Publish Windows $(buildPlatform) $(buildConfiguration) Dependencies Artifacts

- job: PUBLISH_WIN_DEPS
  dependsOn: BUILD_WIN_DEPS
  steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'DEPS_BUILD_WIN_Win32_Release' 
        targetPath: 'Dependencies/Build/'

    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'DEPS_BUILD_WIN_Win32_Debug' 
        targetPath: 'Dependencies/Build/'

    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'DEPS_BUILD_WIN_x64_Release' 
        targetPath: 'Dependencies/Build/'

    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'DEPS_BUILD_WIN_x64_Debug' 
        targetPath: 'Dependencies/Build/'

    - task: DeleteFiles@1
      inputs:
        contents: 'Dependencies/Build/tmp'

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'IPLUG2_DEPS_WIN'
        targetPath: 'Dependencies/Build/'
      displayName: Publish Windows Dependencies Artifacts