trigger:
- azure

jobs:
- job: Build
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.13'
        isMac: true
#      windows:
#        imageName: 'vs2017-win2016'
#        isWindows: true
#      linux:
#      imageName: 'ubuntu-16.04'
#        isLinux: true

  pool:
    vmImage: $(imageName)
    
  steps:
  - checkout: self

  # - bash: |
  #     ./Dependencies/IGraphics/build-igraphics-libs-mac.sh
  #   condition: variables.isMac
  #   displayName: Build macOS IGraphics Dependencies

  - bash: |
      wget http://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-apple-darwin.tar.xz
      mkdir ./Dependencies/Build
      mkdir ./Dependencies/Build/tmp
      tar -xf clang+llvm-7.0.0-x86_64-apple-darwin.tar.xz -C ./Dependencies/Build/tmp
      export PATH=$HOME/Dependencies/Build/tmp/clang+llvm-7.0.0-x86_64-apple-darwin/bin:$PATH
      echo "##vso[task.setvariable variable=PATH]$PATH"
    condition: variables.isMac
    displayName: Build macOS Extras Dependencies - LLVM

  - bash: |
      echo $PATH
      file ./Dependencies/Build/tmp/clang+llvm-7.0.0-x86_64-apple-darwin/bin/llvm-config
      llvm-config
      # cd ./Dependencies/Extras/faust/
      # ./build-faust-mac.sh
    condition: variables.isMac
    displayName: Build macOS Extras Dependencies - FAUST

  # - bash: |
  #     cd ./Dependencies/Extras/civetweb/
  #     ./build-civetweb-mac.sh
  #   condition: variables.isMac
  #   displayName: Build macOS Extras Dependencies - CIVETWEB

  # - bash: |
  #     cd ./Dependencies/
  #     tar -cvzf iplug2_deps_macOS.tar.gz mac
  #   condition: variables.isMac
  #   displayName: Package macOS Dependencies Artifacts

  # - task: PublishPipelineArtifact@0
  #   inputs:
  #     artifactName: 'IPLUG2_DEPS_MACOS'
  #     targetPath: './Dependencies/Build/iplug2_deps_macOS.tar.gz'
  #   condition: variables.isMac
  #   displayName: Publish macOS Dependencies Artifacts

  
#  - task: Xcode@5
#    inputs:
#      actions: 'build'
#      scheme: 'APP'
#      sdk: 'macosx10.13'
#      configuration: 'Release'
#      xcWorkspacePath: 'Tests/IGraphicsTest/IGraphicsTest.xcworkspace'
#      xcodeVersion: "9"
