trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'APP'
    sdk: 'macosx10.13'
    configuration: 'Release'
    xcWorkspacePath: 'Tests/IGraphicsTest/IGraphicsTest.xcworkspace'
    xcodeVersion: "9"
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'APP'
    sdk: 'macosx10.13'
    configuration: 'Release'
    xcWorkspacePath: 'Tests/IGraphicsStressTest/IGraphicsStressTest.xcworkspace'
    xcodeVersion: "9"
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'APP'
    sdk: 'macosx10.13'
    configuration: 'Release'
    xcWorkspacePath: 'Examples/IPlugControls/IPlugControls.xcworkspace'
    xcodeVersion: "9"
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'APP'
    sdk: 'macosx10.13'
    configuration: 'Release'
    xcWorkspacePath: 'Examples/IPlugEffect/IPlugEffect.xcworkspace'
    xcodeVersion: "9"
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'APP'
    sdk: 'macosx10.13'
    configuration: 'Release'
    xcWorkspacePath: 'Examples/IPlugInstrument/IPlugInstrument.xcworkspace'
    xcodeVersion: "9"

